-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'johnny@appleseed.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'johnny@appleseed.com',
        TRUE);

INSERT INTO projects (title, description, manager, deadline, status)
VALUES ('Project Alpha', 
        'Description for Project Alpha.', 
        'Manager1', 
        '2023-12-31', 
        'planned'),
        ('Project Beta', 
        'Description for Project Beta.', 
        'Manager2', 
        '2023-11-30', 
        'in progress'),
        ('Project Gamma', 
        'Description for Project Gamma.', 
        'Manager3', 
        '2023-10-31', 
        'completed'),
        ('Project Delta', 
        'Description for Project Delta.', 
        'Manager1', 
        '2024-01-31', 
        'planned'),
        ('Project Epsilon', 
        'Description for Project Epsilon.', 
        'Manager2', 
        '2024-02-28', 
        'in progress'),
        ('Project Zeta', 
        'Description for Project Zeta.', 
        'Manager3', 
        '2024-03-31', 
        'completed'),
        ('Project Eta', 
        'Description for Project Eta.', 
        'Manager1', 
        '2024-04-30', 
        'planned'),
        ('Project Theta', 
        'Description for Project Theta.', 
        'Manager2', 
        '2024-05-31', 
        'in progress'),
        ('Project Iota', 
        'Description for Project Iota.', 
        'Manager3', 
        '2024-06-30', 
        'completed'),
        ('Project Kappa', 
        'Description for Project Kappa.', 
        'Manager1', 
        '2024-07-31', 
        'planned'),
        ('Project Lambda', 
        'Description for Project Lambda.', 
        'Manager2', 
        '2024-08-31', 
        'in progress'),
        ('Project Mu', 
        'Description for Project Mu.', 
        'Manager3', 
        '2024-09-30', 
        'completed');

